kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-admin-group
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: admin-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
